# Generated by Django 3.0.7 on 2020-06-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('short_description', models.CharField(max_length=300)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('difficult', 'difficult'), ('expert', 'expert')], default='easy', max_length=10)),
                ('food_type', models.CharField(choices=[('vegetarian', 'vegetarian'), ('non', 'non-vegetarian')], default='vegetarian', max_length=15)),
                ('serve', models.PositiveSmallIntegerField(default=1)),
                ('menu', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('quickbite', 'Quickbite'), ('dinner', 'Dinner'), ('desert', 'Desert'), ('beverage', 'Beverage')], default='lunch', max_length=15)),
                ('ingredients', models.TextField()),
                ('procedure', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
