# Generated by Django 3.0.7 on 2020-06-18 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
