# Generated by Django 3.0.7 on 2020-06-21 17:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200618_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='ingredients',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='make',
            name='procedure',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
