# Generated by Django 3.0.7 on 2020-06-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200624_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='comman',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
