# Generated by Django 3.0.7 on 2020-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200624_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='menu',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Quickbite', 'Quickbite'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage')], default='Dessert', max_length=15),
        ),
    ]
