# Generated by Django 3.0.7 on 2020-07-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200701_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='thunbnail_image',
            field=models.ImageField(default='/images/ip-3.jpg', upload_to='images/'),
        ),
    ]
