# Generated by Django 3.0.7 on 2020-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200701_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make',
            name='thunbnail_image',
        ),
        migrations.AddField(
            model_name='make',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
