# Generated by Django 3.0.7 on 2020-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200701_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='Recipe_video',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
