# Generated by Django 3.0.7 on 2020-07-02 07:25

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_make_recipe_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='ingredients',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='make',
            name='procedure',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='images/Profile')),
                ('bio', models.TextField()),
                ('facebook_url', models.CharField(blank=True, max_length=255, null=True)),
                ('instagrm_url', models.CharField(blank=True, max_length=255, null=True)),
                ('snapchat_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
