# Generated by Django 3.0.7 on 2020-07-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200702_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagrm_url',
            new_name='instagram_url',
        ),
    ]
