# Generated by Django 3.0.7 on 2020-07-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200702_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='thumbnail_image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/Profile'),
        ),
    ]
