# Generated by Django 3.0.7 on 2020-07-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200704_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='make',
            name='procedure',
            field=models.TextField(),
        ),
    ]
