# Generated by Django 3.0.7 on 2020-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200705_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='procedure',
            field=models.TextField(),
        ),
    ]
